"""Static pools used by the bulk dog generator (app.scripts.generate_dogs)."""

DOG_NAMES = [
    "Bella", "Luna", "Charlie", "Lucy", "Cooper", "Max", "Daisy", "Bailey", "Sadie", "Lola",
    "Buddy", "Rocky", "Molly", "Tucker", "Bear", "Duke", "Sophie", "Toby", "Chloe", "Maggie",
    "Riley", "Zoe", "Jack", "Stella", "Lily", "Murphy", "Ruby", "Oliver", "Penny", "Milo",
    "Roxy", "Bentley", "Coco", "Leo", "Rosie", "Oscar", "Lulu", "Winston", "Hazel", "Sammy",
    "Harley", "Piper", "Bruno", "Zoey", "Finn", "Maddie", "Louie", "Nala", "Gus", "Marley",
    "Ollie", "Mia", "Henry", "Belle", "Otis", "Olive", "Diesel", "Pepper", "Buster", "Willow",
    "Beau", "Sasha", "Bandit", "Layla", "Jax", "Annie", "Apollo", "Gracie", "Loki", "Honey",
    "Ace", "Abby", "Tank", "Roxie", "Moose", "Athena", "Kobe", "Dixie", "Romeo", "Mocha",
    "Zeus", "Cleo", "Thor", "Sandy", "Shadow", "Phoebe", "Scout", "Minnie", "Blue", "Ginger",
    "Chase", "Holly", "Hunter", "Mabel", "Bowser", "June", "Theo", "Pearl", "Jasper", "Roxanne",
    "Koda", "Macy", "Pongo", "Nova", "Cash", "Goose", "Reese", "Frankie", "Sully", "Poppy",
    "Sarge", "Iris", "Brutus", "Sky", "Boomer", "Trixie", "Gunner", "Amber", "Yoshi", "Wren",
    "Banjo", "Cleopatra", "Echo", "Juno", "Fitz", "Kiki", "Pickles", "Tilly", "Biscuit", "Goldie",
    "Waffles", "Peaches", "Mango", "Olive", "Saffron", "Truffle", "Pumpkin", "Pancake", "Mochi", "Suki",
    "Hank", "Doc", "Earl", "Gus", "Walter", "Frank", "Stanley", "Norm", "Vinnie", "Pete",
    "Kona", "Sage", "Wiley", "Indy", "Kai", "Quinn", "Remy", "Skye", "Tess", "Vega",
    "Archie", "Boo", "Chip", "Dash", "Elmo", "Fozzie", "Gizmo", "Hugo", "Ivy", "Jelly",
    "Kobi", "Lyla", "Mojo", "Niko", "Opal", "Phantom", "Quincy", "Rufus", "Snickers", "Tilly",
    "Ursa", "Velvet", "Walnut", "Xena", "Yogi", "Zelda", "Atlas", "Birdie", "Cricket", "Dottie",
    "Ellie", "Fern", "Gigi", "Hattie", "Inkblot", "Juniper", "Klaus", "Lottie", "Memphis", "Noodle",
]

TRAITS = [
    "playful", "loyal", "goofy", "anxious", "food-motivated", "couch potato", "ball-obsessed",
    "trail buddy", "park royalty", "leash-puller", "lap dog", "velcro dog", "social butterfly",
    "shy", "barky", "quiet", "smart", "stubborn", "cuddly", "protective", "independent",
    "high energy", "low energy", "reactive", "easygoing", "rescue", "senior", "puppy energy",
    "great with kids", "good with cats", "loves water", "afraid of vacuums", "treat thief",
    "sock collector", "frisbee fanatic", "early riser", "night owl", "snorer", "snuggler",
    "show-off", "lazy genius",
]

CITIES = [
    "New York, NY", "Brooklyn, NY", "Los Angeles, CA", "San Francisco, CA", "Oakland, CA",
    "Chicago, IL", "Austin, TX", "Houston, TX", "Dallas, TX", "Seattle, WA",
    "Portland, OR", "Denver, CO", "Boulder, CO", "Boston, MA", "Cambridge, MA",
    "Philadelphia, PA", "Pittsburgh, PA", "Atlanta, GA", "Miami, FL", "Orlando, FL",
    "Washington, DC", "Arlington, VA", "Minneapolis, MN", "Madison, WI", "Nashville, TN",
    "Charlotte, NC", "Raleigh, NC", "Phoenix, AZ", "San Diego, CA", "Salt Lake City, UT",
]

FIRST_NAMES = [
    "Alex", "Avery", "Blake", "Cameron", "Casey", "Charlie", "Drew", "Emerson", "Finley", "Harper",
    "Hayden", "Jamie", "Jordan", "Kai", "Kendall", "Logan", "Morgan", "Parker", "Peyton", "Quinn",
    "Reese", "Riley", "Robin", "Rowan", "Sage", "Sawyer", "Skyler", "Taylor", "Aiden", "Amelia",
    "Ava", "Benjamin", "Caroline", "Daniel", "Eleanor", "Ethan", "Grace", "Henry", "Isabella", "James",
    "Julia", "Liam", "Lily", "Lucas", "Maya", "Mia", "Noah", "Olivia", "Owen", "Sophia",
    "Theodore", "Violet", "William", "Zoe", "Andrea", "Bryan", "Carmen", "Diego", "Elena", "Felipe",
    "Gabriela", "Hugo", "Isla", "Jin", "Khalid", "Leila", "Marcus", "Nadia", "Omar", "Priya",
    "Rashid", "Sana", "Tariq", "Uma", "Viktor", "Wei", "Xiomara", "Yuki", "Zane", "Beth",
    "Carl", "Dana", "Erin", "Frank", "Gina", "Hank", "Ivy", "Jack", "Kara", "Lila",
    "Matt", "Nina", "Otis", "Pete", "Rae", "Stan", "Tess", "Vera", "Will", "Yara",
]

LAST_INITIALS = list("ABCDEFGHJKLMNOPRSTVWY")

LAST_NAMES = [
    "Anderson", "Bennett", "Carter", "Diaz", "Evans", "Foster", "Garcia", "Hayes",
    "Iverson", "Jensen", "Kim", "Lopez", "Martinez", "Nguyen", "O'Connor", "Patel",
    "Quinn", "Reyes", "Singh", "Tran", "Underwood", "Vargas", "Walker", "Young",
    "Zhang", "Brooks", "Chen", "Donovan", "Ellis", "Fischer", "Goldberg", "Hassan",
    "Ito", "Jacobson", "Kowalski", "Lee", "Murphy", "Nakamura", "Ortega", "Park",
    "Romano", "Schmidt", "Tanaka", "Vasquez", "Williams", "Xu", "Yamamoto", "Zimmerman",
]

# Pick at most one per dog from each anchor group — keeps trait sets coherent.
AGE_TRAITS = ["puppy energy", "senior"]
ENERGY_TRAITS = ["high energy", "low energy"]
ORIGIN_TRAITS = ["rescue"]
ANCHOR_ALL = set(AGE_TRAITS) | set(ENERGY_TRAITS) | set(ORIGIN_TRAITS)

ACTIVITIES = [
    "chasing leaves", "stealing socks", "sunning on the deck", "patrolling the backyard",
    "supervising dinner prep", "alerting us to the mailman", "trying to catch squirrels",
    "rolling in mystery substances", "greeting every dog at the park", "snoring on the couch",
    "side-eyeing the cat", "waiting for crumbs", "burying treats in the carpet",
    "negotiating for table scraps", "guarding the front window", "dropping toys at strangers' feet",
]

ADOPTION_PHRASES = [
    "from the local shelter", "during the pandemic", "off a friend's farm", "from a rescue in {city}",
    "after their previous family moved", "as a foster fail", "from a roadside rest stop",
    "after spotting them at an adoption event", "from a breed-specific rescue",
]

MUTT_DESCRIPTORS = [
    "DNA-test-pending mutt", "100% mystery mix", "rescue of unspecified lineage",
    "all-American mutt", "neighborhood gremlin", "mutt extraordinaire",
    "good ol' mutt", "shelter special", "everything-bagel of a dog",
]

MIXED_PHRASE_TEMPLATES = [
    "{primary} mix",
    "mostly {primary}, partly chaos",
    "{primary} blend (and a few opinions)",
    "{primary} with {secondary} energy",
    "the world's most enthusiastic {primary} mix",
]

# Map our slug (slugify of breed name) -> dog.ceo path component used in
# /api/breed/{path}/images/random/{n}. Only popular breeds covered; misses
# fall through to /api/breeds/image/random/{n} for a random breed photo.
BREED_TO_DOGCEO = {
    "affenpinscher": "affenpinscher",
    "afghan-hound": "hound/afghan",
    "airedale-terrier": "airedale",
    "akita": "akita",
    "alaskan-malamute": "malamute",
    "american-eskimo-dog": "eskimo",
    "american-pit-bull-terrier": "pitbull",
    "american-staffordshire-terrier": "terrier/american",
    "australian-cattle-dog": "cattledog/australian",
    "australian-kelpie": "kelpie",
    "australian-shepherd": "australian/shepherd",
    "australian-terrier": "terrier/australian",
    "basenji": "basenji",
    "basset-hound": "hound/basset",
    "beagle": "beagle",
    "bedlington-terrier": "terrier/bedlington",
    "belgian-malinois": "malinois",
    "belgian-tervuren": "tervuren",
    "bernese-mountain-dog": "mountain/bernese",
    "bichon-frise": "frise/bichon",
    "bloodhound": "hound/blood",
    "bluetick-coonhound": "bluetick",
    "border-collie": "collie/border",
    "border-terrier": "terrier/border",
    "borzoi": "borzoi",
    "boston-terrier": "bulldog/boston",
    "bouvier-des-flandres": "bouvier",
    "boxer": "boxer",
    "briard": "briard",
    "brittany": "spaniel/brittany",
    "bull-terrier": "bullterrier",
    "bulldog": "bulldog/english",
    "bullmastiff": "mastiff/bull",
    "cairn-terrier": "terrier/cairn",
    "cardigan-welsh-corgi": "corgi/cardigan",
    "cavalier-king-charles-spaniel": "spaniel/cocker",
    "chesapeake-bay-retriever": "retriever/chesapeake",
    "chihuahua": "chihuahua",
    "chow-chow": "chow",
    "clumber-spaniel": "clumber",
    "cocker-spaniel": "spaniel/cocker",
    "collie": "collie/border",
    "curly-coated-retriever": "retriever/curly",
    "dachshund": "dachshund",
    "dalmatian": "dalmatian",
    "dandie-dinmont-terrier": "terrier/dandie",
    "doberman-pinscher": "doberman",
    "english-bulldog": "bulldog/english",
    "english-mastiff": "mastiff/english",
    "english-setter": "setter/english",
    "english-springer-spaniel": "springer/english",
    "entlebucher-mountain-dog": "entlebucher",
    "finnish-lapphund": "finnish/lapphund",
    "flat-coated-retriever": "retriever/flatcoated",
    "french-bulldog": "bulldog/french",
    "german-shepherd": "germanshepherd",
    "german-shorthaired-pointer": "pointer/german",
    "giant-schnauzer": "schnauzer/giant",
    "golden-retriever": "retriever/golden",
    "goldendoodle": "labradoodle",
    "gordon-setter": "setter/gordon",
    "great-dane": "dane/great",
    "great-pyrenees": "pyrenees",
    "greater-swiss-mountain-dog": "mountain/swiss",
    "greyhound": "greyhound/italian",
    "havanese": "havanese",
    "ibizan-hound": "hound/ibizan",
    "irish-setter": "setter/irish",
    "irish-terrier": "terrier/irish",
    "irish-water-spaniel": "spaniel/irish",
    "irish-wolfhound": "wolfhound/irish",
    "italian-greyhound": "greyhound/italian",
    "jack-russell-terrier": "terrier/russell",
    "japanese-chin": "spaniel/japanese",
    "keeshond": "keeshond",
    "kerry-blue-terrier": "terrier/kerryblue",
    "komondor": "komondor",
    "kuvasz": "kuvasz",
    "labradoodle": "labradoodle",
    "labrador-retriever": "labrador",
    "lakeland-terrier": "terrier/lakeland",
    "leonberger": "leonberg",
    "lhasa-apso": "lhasa",
    "maltese": "maltese",
    "mastiff": "mastiff/english",
    "miniature-pinscher": "pinscher/miniature",
    "miniature-schnauzer": "schnauzer/miniature",
    "newfoundland": "newfoundland",
    "norfolk-terrier": "terrier/norfolk",
    "norwegian-elkhound": "elkhound/norwegian",
    "norwich-terrier": "terrier/norwich",
    "old-english-sheepdog": "sheepdog/english",
    "otterhound": "otterhound",
    "papillon": "papillon",
    "parson-russell-terrier": "terrier/russell",
    "pekingese": "pekinese",
    "pembroke-welsh-corgi": "pembroke",
    "plott": "hound/plott",
    "pomeranian": "pomeranian",
    "poodle": "poodle/standard",
    "pug": "pug",
    "puggle": "puggle",
    "redbone-coonhound": "redbone",
    "rhodesian-ridgeback": "ridgeback/rhodesian",
    "rottweiler": "rottweiler",
    "russell-terrier": "terrier/russell",
    "saint-bernard": "stbernard",
    "saluki": "saluki",
    "samoyed": "samoyed",
    "schipperke": "schipperke",
    "scottish-deerhound": "deerhound/scottish",
    "scottish-terrier": "terrier/scottish",
    "sealyham-terrier": "terrier/sealyham",
    "shetland-sheepdog": "sheepdog/shetland",
    "shiba-inu": "shiba",
    "shih-tzu": "shihtzu",
    "siberian-husky": "husky",
    "silky-terrier": "terrier/silky",
    "smooth-fox-terrier": "terrier/fox",
    "soft-coated-wheaten-terrier": "terrier/wheaten",
    "spanish-water-dog": "waterdog/spanish",
    "staffordshire-bull-terrier": "bullterrier/staffordshire",
    "tibetan-mastiff": "mastiff/tibetan",
    "tibetan-terrier": "terrier/tibetan",
    "treeing-walker-coonhound": "hound/walker",
    "vizsla": "vizsla",
    "weimaraner": "weimaraner",
    "welsh-springer-spaniel": "spaniel/welsh",
    "welsh-terrier": "terrier/welsh",
    "west-highland-white-terrier": "terrier/westhighland",
    "whippet": "whippet",
    "wire-fox-terrier": "terrier/fox",
    "yorkshire-terrier": "terrier/yorkshire",
}

BIO_ADJECTIVES = [
    "cuddly", "rambunctious", "easygoing", "silly", "adventurous", "polite", "scrappy",
    "regal", "goofy", "thoughtful", "dramatic", "low-key", "exuberant", "deeply serious",
]

BIO_LOVES = [
    "naps", "treats", "the dog park", "car rides", "squeaky toys", "tennis balls",
    "puddles", "muddy paws", "the sound of the front door", "their human's lap",
    "long walks", "fetch", "cheese", "snowstorms", "warm sunbeams",
    "string cheese", "ice cubes", "open windows", "the doorbell (mortal enemy)",
    "rotisserie chicken", "delivery drivers", "the vacuum (mortal enemy)",
]
