"""rescue public page columns

Revision ID: 0cb45e2c95a6
Revises: 2f254cea1911
Create Date: 2026-07-13 05:27:21.907439
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.breed_data import slugify


# revision identifiers, used by Alembic.
revision: str = '0cb45e2c95a6'
down_revision: Union[str, None] = '2f254cea1911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('rescue_profiles', sa.Column('slug', sa.String(length=80), nullable=True))
    op.add_column('rescue_profiles', sa.Column('is_public', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('rescue_profiles', sa.Column('logo_key', sa.String(length=200), nullable=True))
    op.add_column('rescue_profiles', sa.Column('cover_key', sa.String(length=200), nullable=True))

    # Backfill a unique slug from org_name for every existing rescue before the
    # unique index goes on. Oldest first, so the earliest org keeps the base slug.
    conn = op.get_bind()
    rows = conn.execute(
        sa.text("SELECT id, org_name FROM rescue_profiles ORDER BY created_at")
    ).fetchall()
    seen: set[str] = set()
    for rid, org_name in rows:
        base = slugify(org_name or "") or "rescue"
        slug = base
        n = 1
        while slug in seen:
            n += 1
            slug = f"{base}-{n}"
        seen.add(slug)
        conn.execute(
            sa.text("UPDATE rescue_profiles SET slug = :slug WHERE id = :id"),
            {"slug": slug, "id": rid},
        )

    op.create_index(op.f('ix_rescue_profiles_slug'), 'rescue_profiles', ['slug'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rescue_profiles_slug'), table_name='rescue_profiles')
    op.drop_column('rescue_profiles', 'cover_key')
    op.drop_column('rescue_profiles', 'logo_key')
    op.drop_column('rescue_profiles', 'is_public')
    op.drop_column('rescue_profiles', 'slug')
    # ### end Alembic commands ###
