"""add lost report tables

Revision ID: 18b43f3401a4
Revises: 1dc7c0ed5b89
Create Date: 2026-04-12 21:23:15.439960
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18b43f3401a4'
down_revision: Union[str, None] = '1dc7c0ed5b89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lost_report_subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('home_lat', sa.Float(), nullable=False),
    sa.Column('home_lng', sa.Float(), nullable=False),
    sa.Column('radius_km', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lost_report_subscriptions_user_id'), 'lost_report_subscriptions', ['user_id'], unique=False)
    op.create_table('lost_reports',
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('dog_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_lat', sa.Float(), nullable=True),
    sa.Column('last_seen_lng', sa.Float(), nullable=True),
    sa.Column('location_fuzz_m', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('contact_method', sa.String(length=20), nullable=False),
    sa.Column('contact_value', sa.String(length=200), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lost_reports_kind'), 'lost_reports', ['kind'], unique=False)
    op.create_index(op.f('ix_lost_reports_reporter_id'), 'lost_reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_lost_reports_status'), 'lost_reports', ['status'], unique=False)
    op.create_table('lost_report_photos',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['lost_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lost_report_photos_report_id'), 'lost_report_photos', ['report_id'], unique=False)
    op.create_table('lost_report_sightings',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('photo_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['lost_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lost_report_sightings_report_id'), 'lost_report_sightings', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lost_report_sightings_report_id'), table_name='lost_report_sightings')
    op.drop_table('lost_report_sightings')
    op.drop_index(op.f('ix_lost_report_photos_report_id'), table_name='lost_report_photos')
    op.drop_table('lost_report_photos')
    op.drop_index(op.f('ix_lost_reports_status'), table_name='lost_reports')
    op.drop_index(op.f('ix_lost_reports_reporter_id'), table_name='lost_reports')
    op.drop_index(op.f('ix_lost_reports_kind'), table_name='lost_reports')
    op.drop_table('lost_reports')
    op.drop_index(op.f('ix_lost_report_subscriptions_user_id'), table_name='lost_report_subscriptions')
    op.drop_table('lost_report_subscriptions')
    # ### end Alembic commands ###
