"""user species_preference

Revision ID: 2f254cea1911
Revises: 7f66162335ee
Create Date: 2026-07-13 05:12:58.401139
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f254cea1911'
down_revision: Union[str, None] = '7f66162335ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('species_preference', sa.String(length=10), server_default='both', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'species_preference')
    # ### end Alembic commands ###
