"""qr_tags table

Revision ID: 5df77090d354
Revises: 0cb45e2c95a6
Create Date: 2026-07-13 05:36:36.984870
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5df77090d354'
down_revision: Union[str, None] = '0cb45e2c95a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_tags',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('pet_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_tags_code'), 'qr_tags', ['code'], unique=True)
    op.create_index(op.f('ix_qr_tags_pet_id'), 'qr_tags', ['pet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qr_tags_pet_id'), table_name='qr_tags')
    op.drop_index(op.f('ix_qr_tags_code'), table_name='qr_tags')
    op.drop_table('qr_tags')
    # ### end Alembic commands ###
