"""audit: unique constraints for reviews/subscriptions, hot-path indexes

Revision ID: 5f1fa3dd89e0
Revises: c6d7e8f9a0b1
Create Date: 2026-08-15 15:33:41.139648
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f1fa3dd89e0'
down_revision: Union[str, None] = 'c6d7e8f9a0b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Both unique constraints below are being added to tables that until now
    # allowed duplicates, so existing rows have to be collapsed first or the
    # ALTER fails on any populated database. Keep the most recent row in each
    # group — for a park review that is the author's latest opinion, and for a
    # subscription the one the UI would have shown them.
    op.execute(
        """
        DELETE FROM lost_report_subscriptions a
        USING lost_report_subscriptions b
        WHERE a.user_id = b.user_id
          AND (a.created_at, a.id) < (b.created_at, b.id)
        """
    )
    op.execute(
        """
        DELETE FROM park_reviews a
        USING park_reviews b
        WHERE a.park_id = b.park_id
          AND a.author_id = b.author_id
          AND (a.created_at, a.id) < (b.created_at, b.id)
        """
    )

    op.create_unique_constraint('uq_lost_sub_user', 'lost_report_subscriptions', ['user_id'])
    op.create_index('ix_lost_reports_status_lat_lng', 'lost_reports', ['status', 'last_seen_lat', 'last_seen_lng'], unique=False)
    op.create_unique_constraint('uq_park_review_author', 'park_reviews', ['park_id', 'author_id'])
    op.create_index('ix_parks_lat_lng', 'parks', ['lat', 'lng'], unique=False)
    op.create_index(op.f('ix_photos_moderation_status'), 'photos', ['moderation_status'], unique=False)
    op.create_index('ix_votes_voter_week', 'votes', ['voter_id', 'week_bucket'], unique=False)
    op.create_index('ix_votes_week_pet', 'votes', ['week_bucket', 'pet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_votes_week_pet', table_name='votes')
    op.drop_index('ix_votes_voter_week', table_name='votes')
    op.drop_index(op.f('ix_photos_moderation_status'), table_name='photos')
    op.drop_index('ix_parks_lat_lng', table_name='parks')
    op.drop_constraint('uq_park_review_author', 'park_reviews', type_='unique')
    op.drop_index('ix_lost_reports_status_lat_lng', table_name='lost_reports')
    op.drop_constraint('uq_lost_sub_user', 'lost_report_subscriptions', type_='unique')
    # ### end Alembic commands ###
