"""add periodic_tasks table

Revision ID: 866ab1d278cb
Revises: c8bbd3d7e293
Create Date: 2026-07-18 21:54:01.518616
"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.tasks.schedule_defaults import DEFAULT_PERIODIC_TASKS

# revision identifiers, used by Alembic.
revision: str = '866ab1d278cb'
down_revision: Union[str, None] = 'c8bbd3d7e293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periodic_tasks',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('task', sa.String(length=255), nullable=False),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('interval_seconds', sa.Float(), nullable=True),
    sa.Column('minute', sa.String(length=64), server_default='*', nullable=False),
    sa.Column('hour', sa.String(length=64), server_default='*', nullable=False),
    sa.Column('day_of_week', sa.String(length=64), server_default='*', nullable=False),
    sa.Column('day_of_month', sa.String(length=64), server_default='*', nullable=False),
    sa.Column('month_of_year', sa.String(length=64), server_default='*', nullable=False),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('kwargs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('queue', sa.String(length=128), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('one_off', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_run_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_periodic_tasks_name'), 'periodic_tasks', ['name'], unique=True)
    # ### end Alembic commands ###

    # Seed the built-in jobs that used to live in celery_app.conf.beat_schedule
    # so a fresh install schedules exactly as before (now editable). Columns with
    # server_defaults (args/kwargs/enabled/one_off/total_run_count) are omitted.
    seed_table = sa.table(
        "periodic_tasks",
        sa.column("id", postgresql.UUID(as_uuid=True)),
        sa.column("name", sa.String),
        sa.column("task", sa.String),
        sa.column("schedule_type", sa.String),
        sa.column("interval_seconds", sa.Float),
        sa.column("minute", sa.String),
        sa.column("hour", sa.String),
        sa.column("day_of_week", sa.String),
        sa.column("day_of_month", sa.String),
        sa.column("month_of_year", sa.String),
        sa.column("description", sa.String),
    )
    op.bulk_insert(seed_table, [
        {
            "id": uuid.uuid4(),
            "name": job["name"],
            "task": job["task"],
            "schedule_type": job["schedule_type"],
            "interval_seconds": job["interval_seconds"],
            "minute": job["minute"],
            "hour": job["hour"],
            "day_of_week": job["day_of_week"],
            "day_of_month": job["day_of_month"],
            "month_of_year": job["month_of_year"],
            "description": job.get("description"),
        }
        for job in DEFAULT_PERIODIC_TASKS
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_periodic_tasks_name'), table_name='periodic_tasks')
    op.drop_table('periodic_tasks')
    # ### end Alembic commands ###
