"""announcement email opt-out preference

Revision ID: 89c2359c5689
Revises: dbe22d71f290
Create Date: 2026-08-15 17:21:56.626158
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89c2359c5689'
down_revision: Union[str, None] = 'dbe22d71f290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_preferences', sa.Column('announcement_emails', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_preferences', 'announcement_emails')
    # ### end Alembic commands ###
