"""waitlist invite fields

Revision ID: b4596faa50f9
Revises: 866ab1d278cb
Create Date: 2026-07-18 22:36:37.268176
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4596faa50f9'
down_revision: Union[str, None] = '866ab1d278cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waitlist_entries', sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('waitlist_entries', sa.Column('invite_code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waitlist_entries', 'invite_code')
    op.drop_column('waitlist_entries', 'invited_at')
    # ### end Alembic commands ###
