"""add news posts

Seeds the table with the three articles that previously lived as a static
array in the marketing NewsPage, so existing deploys keep their news history.

Revision ID: c8bbd3d7e293
Revises: 4e7017a3294b
Create Date: 2026-07-18 13:38:24.382480
"""
import uuid
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8bbd3d7e293'
down_revision: Union[str, None] = '4e7017a3294b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_posts',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('link_url', sa.String(length=300), nullable=True),
    sa.Column('link_label', sa.String(length=100), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Carry over the previously hard-coded marketing posts.
    news_posts = sa.table(
        'news_posts',
        sa.column('id', sa.UUID()),
        sa.column('title', sa.String()),
        sa.column('body', sa.Text()),
        sa.column('tag', sa.String()),
        sa.column('link_url', sa.String()),
        sa.column('link_label', sa.String()),
        sa.column('is_published', sa.Boolean()),
        sa.column('published_at', sa.DateTime(timezone=True)),
    )
    op.bulk_insert(news_posts, [
        {
            'id': uuid.uuid4(),
            'title': 'Fetchpawz outgrew the swipe feed',
            'body': (
                'The game is still the heart of it — swipe, vote, crown a weekly '
                'top pet — but the beta now goes well past the feed. Find nearby '
                'dog parks, check in, and set up playdates. Order a QR tag that '
                'links your pet\'s collar to their page. Browse rescues on the '
                'map and donate to one in a couple of taps, right in the app. '
                'And Lost & Found now alerts the neighborhood the minute a pet '
                'goes missing. Swipe for fun, rescue for real — that\'s the idea.'
            ),
            'tag': 'Product',
            'link_url': '/',
            'link_label': 'Join the waitlist',
            'is_published': True,
            'published_at': datetime(2026, 7, 15, tzinfo=timezone.utc),
        },
        {
            'id': uuid.uuid4(),
            'title': 'Fetchpawz enters private beta',
            'body': (
                'The first invites went out. A small group of pet owners and '
                'rescue partners is using Fetchpawz daily now, and their '
                'feedback has already changed how the feed works. A public '
                'launch date comes next.'
            ),
            'tag': 'Milestone',
            'link_url': None,
            'link_label': None,
            'is_published': True,
            'published_at': datetime(2026, 6, 15, tzinfo=timezone.utc),
        },
        {
            'id': uuid.uuid4(),
            'title': 'Partnering with rescues for launch',
            'body': (
                'Adoption is the whole point of Fetchpawz, so rescues got the '
                'first look. Our earliest partners are setting up their '
                'profiles now, and their adoptable pets will be in the feed on '
                'day one. If you run a rescue and want in, applications are open.'
            ),
            'tag': 'Partnerships',
            'link_url': '/signup-rescue',
            'link_label': 'Apply as a rescue',
            'is_published': True,
            'published_at': datetime(2026, 5, 15, tzinfo=timezone.utc),
        },
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_posts')
    # ### end Alembic commands ###
