"""bind invite codes to an invited email

Revision ID: dbe22d71f290
Revises: 5f1fa3dd89e0
Create Date: 2026-08-15 16:51:58.336076
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbe22d71f290'
down_revision: Union[str, None] = '5f1fa3dd89e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite_codes', sa.Column('invited_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invite_codes', 'invited_email')
    # ### end Alembic commands ###
