"""Canonical breed reference list used by both the Alembic seeder and
runtime helpers. Sourced from AKC recognized breeds plus common mixes.
Format: (name, group). Group is nullable — free to extend later."""

BREED_SEED: list[tuple[str, str | None]] = [
    ("Affenpinscher", "Toy"),
    ("Afghan Hound", "Hound"),
    ("Airedale Terrier", "Terrier"),
    ("Akita", "Working"),
    ("Alaskan Malamute", "Working"),
    ("American Bulldog", "Working"),
    ("American Eskimo Dog", "Non-Sporting"),
    ("American Foxhound", "Hound"),
    ("American Pit Bull Terrier", "Terrier"),
    ("American Staffordshire Terrier", "Terrier"),
    ("American Water Spaniel", "Sporting"),
    ("Anatolian Shepherd Dog", "Working"),
    ("Australian Cattle Dog", "Herding"),
    ("Australian Kelpie", "Herding"),
    ("Australian Shepherd", "Herding"),
    ("Australian Terrier", "Terrier"),
    ("Basenji", "Hound"),
    ("Basset Hound", "Hound"),
    ("Beagle", "Hound"),
    ("Bearded Collie", "Herding"),
    ("Beauceron", "Herding"),
    ("Bedlington Terrier", "Terrier"),
    ("Belgian Malinois", "Herding"),
    ("Belgian Sheepdog", "Herding"),
    ("Belgian Tervuren", "Herding"),
    ("Bernese Mountain Dog", "Working"),
    ("Bichon Frise", "Non-Sporting"),
    ("Black and Tan Coonhound", "Hound"),
    ("Black Russian Terrier", "Working"),
    ("Bloodhound", "Hound"),
    ("Blue Heeler", "Herding"),
    ("Bluetick Coonhound", "Hound"),
    ("Boerboel", "Working"),
    ("Border Collie", "Herding"),
    ("Border Terrier", "Terrier"),
    ("Borzoi", "Hound"),
    ("Boston Terrier", "Non-Sporting"),
    ("Bouvier des Flandres", "Herding"),
    ("Boxer", "Working"),
    ("Boykin Spaniel", "Sporting"),
    ("Briard", "Herding"),
    ("Brittany", "Sporting"),
    ("Brussels Griffon", "Toy"),
    ("Bulldog", "Non-Sporting"),
    ("Bullmastiff", "Working"),
    ("Bull Terrier", "Terrier"),
    ("Cairn Terrier", "Terrier"),
    ("Cane Corso", "Working"),
    ("Cardigan Welsh Corgi", "Herding"),
    ("Catahoula Leopard Dog", "Herding"),
    ("Cavalier King Charles Spaniel", "Toy"),
    ("Cesky Terrier", "Terrier"),
    ("Chesapeake Bay Retriever", "Sporting"),
    ("Chihuahua", "Toy"),
    ("Chinese Crested", "Toy"),
    ("Chinese Shar-Pei", "Non-Sporting"),
    ("Chinook", "Working"),
    ("Chow Chow", "Non-Sporting"),
    ("Clumber Spaniel", "Sporting"),
    ("Cocker Spaniel", "Sporting"),
    ("Collie", "Herding"),
    ("Coton de Tulear", "Non-Sporting"),
    ("Curly-Coated Retriever", "Sporting"),
    ("Dachshund", "Hound"),
    ("Dalmatian", "Non-Sporting"),
    ("Dandie Dinmont Terrier", "Terrier"),
    ("Doberman Pinscher", "Working"),
    ("Dogo Argentino", "Working"),
    ("Dogue de Bordeaux", "Working"),
    ("English Bulldog", "Non-Sporting"),
    ("English Cocker Spaniel", "Sporting"),
    ("English Foxhound", "Hound"),
    ("English Mastiff", "Working"),
    ("English Setter", "Sporting"),
    ("English Springer Spaniel", "Sporting"),
    ("English Toy Spaniel", "Toy"),
    ("Entlebucher Mountain Dog", "Herding"),
    ("Field Spaniel", "Sporting"),
    ("Finnish Lapphund", "Herding"),
    ("Finnish Spitz", "Non-Sporting"),
    ("Flat-Coated Retriever", "Sporting"),
    ("French Bulldog", "Non-Sporting"),
    ("German Pinscher", "Working"),
    ("German Shepherd", "Herding"),
    ("German Shorthaired Pointer", "Sporting"),
    ("German Wirehaired Pointer", "Sporting"),
    ("Giant Schnauzer", "Working"),
    ("Glen of Imaal Terrier", "Terrier"),
    ("Golden Retriever", "Sporting"),
    ("Goldendoodle", "Mixed"),
    ("Gordon Setter", "Sporting"),
    ("Great Dane", "Working"),
    ("Great Pyrenees", "Working"),
    ("Greater Swiss Mountain Dog", "Working"),
    ("Greyhound", "Hound"),
    ("Harrier", "Hound"),
    ("Havanese", "Toy"),
    ("Ibizan Hound", "Hound"),
    ("Icelandic Sheepdog", "Herding"),
    ("Irish Red and White Setter", "Sporting"),
    ("Irish Setter", "Sporting"),
    ("Irish Terrier", "Terrier"),
    ("Irish Water Spaniel", "Sporting"),
    ("Irish Wolfhound", "Hound"),
    ("Italian Greyhound", "Toy"),
    ("Jack Russell Terrier", "Terrier"),
    ("Japanese Chin", "Toy"),
    ("Keeshond", "Non-Sporting"),
    ("Kerry Blue Terrier", "Terrier"),
    ("Komondor", "Working"),
    ("Kuvasz", "Working"),
    ("Labradoodle", "Mixed"),
    ("Labrador Retriever", "Sporting"),
    ("Lagotto Romagnolo", "Sporting"),
    ("Lakeland Terrier", "Terrier"),
    ("Leonberger", "Working"),
    ("Lhasa Apso", "Non-Sporting"),
    ("Lowchen", "Non-Sporting"),
    ("Maltese", "Toy"),
    ("Manchester Terrier", "Terrier"),
    ("Mastiff", "Working"),
    ("Miniature American Shepherd", "Herding"),
    ("Miniature Bull Terrier", "Terrier"),
    ("Miniature Pinscher", "Toy"),
    ("Miniature Schnauzer", "Terrier"),
    ("Neapolitan Mastiff", "Working"),
    ("Newfoundland", "Working"),
    ("Norfolk Terrier", "Terrier"),
    ("Norwegian Buhund", "Herding"),
    ("Norwegian Elkhound", "Hound"),
    ("Norwegian Lundehund", "Non-Sporting"),
    ("Norwich Terrier", "Terrier"),
    ("Nova Scotia Duck Tolling Retriever", "Sporting"),
    ("Old English Sheepdog", "Herding"),
    ("Otterhound", "Hound"),
    ("Papillon", "Toy"),
    ("Parson Russell Terrier", "Terrier"),
    ("Pekingese", "Toy"),
    ("Pembroke Welsh Corgi", "Herding"),
    ("Petit Basset Griffon Vendeen", "Hound"),
    ("Pharaoh Hound", "Hound"),
    ("Plott", "Hound"),
    ("Pointer", "Sporting"),
    ("Polish Lowland Sheepdog", "Herding"),
    ("Pomeranian", "Toy"),
    ("Poodle", "Non-Sporting"),
    ("Portuguese Water Dog", "Working"),
    ("Pug", "Toy"),
    ("Puggle", "Mixed"),
    ("Puli", "Herding"),
    ("Pyrenean Shepherd", "Herding"),
    ("Rat Terrier", "Terrier"),
    ("Redbone Coonhound", "Hound"),
    ("Rhodesian Ridgeback", "Hound"),
    ("Rottweiler", "Working"),
    ("Russell Terrier", "Terrier"),
    ("Saint Bernard", "Working"),
    ("Saluki", "Hound"),
    ("Samoyed", "Working"),
    ("Schipperke", "Non-Sporting"),
    ("Scottish Deerhound", "Hound"),
    ("Scottish Terrier", "Terrier"),
    ("Sealyham Terrier", "Terrier"),
    ("Shetland Sheepdog", "Herding"),
    ("Shiba Inu", "Non-Sporting"),
    ("Shih Tzu", "Toy"),
    ("Siberian Husky", "Working"),
    ("Silky Terrier", "Toy"),
    ("Skye Terrier", "Terrier"),
    ("Sloughi", "Hound"),
    ("Smooth Fox Terrier", "Terrier"),
    ("Soft Coated Wheaten Terrier", "Terrier"),
    ("Spanish Water Dog", "Herding"),
    ("Spinone Italiano", "Sporting"),
    ("Staffordshire Bull Terrier", "Terrier"),
    ("Standard Schnauzer", "Working"),
    ("Sussex Spaniel", "Sporting"),
    ("Swedish Vallhund", "Herding"),
    ("Tibetan Mastiff", "Working"),
    ("Tibetan Spaniel", "Non-Sporting"),
    ("Tibetan Terrier", "Non-Sporting"),
    ("Toy Fox Terrier", "Toy"),
    ("Treeing Walker Coonhound", "Hound"),
    ("Vizsla", "Sporting"),
    ("Weimaraner", "Sporting"),
    ("Welsh Springer Spaniel", "Sporting"),
    ("Welsh Terrier", "Terrier"),
    ("West Highland White Terrier", "Terrier"),
    ("Whippet", "Hound"),
    ("Wire Fox Terrier", "Terrier"),
    ("Wirehaired Pointing Griffon", "Sporting"),
    ("Wirehaired Vizsla", "Sporting"),
    ("Xoloitzcuintli", "Non-Sporting"),
    ("Yorkshire Terrier", "Toy"),
]


def slugify(name: str) -> str:
    out = []
    prev_dash = False
    for ch in name.lower():
        if ch.isalnum():
            out.append(ch)
            prev_dash = False
        elif not prev_dash:
            out.append("-")
            prev_dash = True
    return "".join(out).strip("-")
